title: My company
author: me
email: test@test.nl
description: > # this means to ignore newlines until "baseurl:"
  test decription
  with multiple lines

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
